### ISSUE TITLE
Charts available on ArtifactHub, but not in the Charts.yaml

### ISSUE THREAD

**Issue by shrimpgo** [bman46/CTFd-Helm#55]
Hello!

Today I checked the latest version in ArtifactHub and showed me the version 0.8.4, but when I tried to pull it, I received the error message saying `not found`. At repo, in Charts.yaml file, the version still 0.6.3. If I pull this version, am I using the latest version?

Thanks!

**Comment by bman46** [comment]
This may be because you are pulling the chart directly via git. You should still have the latest version doing it that way, just pull the latest from the main branch.

The main reason behind this is because I use CI/CD to package the chart and publish it to a GitHub package via OCI. ArtifactHub pulls the image from GitHub packages which uses the version tag of the release instead of the one in the chart.yaml. Ideally, the GitHub action would commit the correct version to the main branch, but I haven't gotten around to setting that up.
